[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev:client"
  framework = "#custom"
  targetPort = 5173
  port = 8888
  publish = "client/dist"
  autoLaunch = true
